### PR TITLE
Restyling proposal

### PR DESCRIPTION
**Pull request by SvMak**
- update bootstrap to v5.3.3;
- views refactoring;
- made dark simple design(not final, can be used as a temporary stage);
- fix select2 search.

I would be happy for your reviews.

### CODE REVIEW

**Comment by jamesward** [comment]
Wowww! This is amazing! I really appreciate this. I gave it a quick test and it looks great and is such a needed upgrade.  I don't want to ask too much as this alone is a huge upgrade. But if you want, here are two additional changes that'd be nice:
- Toggle for light-mode & dark mode. The dark mode looks great but I'm a light-mode kinda person.  Can we default to system settings? (not even sure if that is possible in the web)
- The page on my 1080p display requires scrolling to get to the WebJar list. Could we compact the vertical layout so that the top of the list is visible on a 1080p display?

If that is too much to ask, no worries as this is already a big improvement.  Thanks again! This is a massive contribution which I'm very grateful for!

**Comment by SvMak** [comment]
> Wowww! This is amazing! I really appreciate this. I gave it a quick test and it looks great and is such a needed upgrade. I don't want to ask too much as this alone is a huge upgrade. But if you want, here are two additional changes that'd be nice:
> 
> * Toggle for light-mode & dark mode. The dark mode looks great but I'm a light-mode kinda person.  Can we default to system settings? (not even sure if that is possible in the web)
> * The page on my 1080p display requires scrolling to get to the WebJar list. Could we compact the vertical layout so that the top of the list is visible on a 1080p display?
> 
> If that is too much to ask, no worries as this is already a big improvement. Thanks again! This is a massive contribution which I'm very grateful for!

Yes, sure, I'll do it.

**Comment by SvMak** [comment]
@jamesward Could you please check the latest changes?

**Comment by SvMak** [comment]
> Looking good! I might make a few tweaks after merge but this is great :)
> 
> I'd like to promote your great work when I share the redesign on twitter/linkedin/bluesky. So let me know your handles if you want me to mention you.

That would be great, thank you!

**Comment by SvMak** [comment]
@jamesward

Do you have any information on how often people use the `/all` page? - if often, it would be nice to add pagination to it.

Could you ask people to write some reviews about webjars project, we could add a testimonials section to the website?

**Comment by jamesward** [comment]
Opened a new issue to discuss `/all` https://github.com/webjars/webjars/issues/2104

**Pull request merged**
