### PR TITLE
Support for CC-BY-3.0 license

### PR DESCRIPTION
**Pull request by platypii**
Fix for Issue #1903 

The fairly popular package `spdx-exceptions` which is a downstream dependency of `npm` and other other packages is not currently deployable with webjars.

It is licensed as CC-BY-3.0 and is the only package downstream of npm that is not already in the approved licenses for webjars.

This PR adds the CC-BY-3.0 license to the list of webjar approved licenses.

As an example of similar projects allowing this license as open source compatible: https://github.com/bbc/apache2-license-checker/blob/master/scripts/whitelist.js

Let me know if I can help with anything on this. Thanks!

### CODE REVIEW

**Comment by jamesward** [comment]
I appreciate you working on this, however it won't work unfortunately. We deploy through BinTray and they do not allow the `CC-BY-3.0` license: https://bintray.com/docs/api/#url_licenses

I've asked them to add this but so far they haven't wanted to. :(

In the meantime we will have to use Classic WebJars for these dependencies.

**Comment by platypii** [comment]
Ah bummer! I'll see about pinging them again just to keep the pressure on :-)

I'll take a look at classic webjars to see if I can work around it that way. Although if I import a package like `org.webjars.npm / npm` and it has a downstream dependency on `org.webjars.npm / spdx-exceptions` then a classic won't actually solve the problem without a manual override, right?

**Comment by jamesward** [comment]
Yeah, that is right. :(

**Comment by jamesward** [comment]
They actually have `CC0-1.0` now so maybe that means they will add `CC-BY-3.0`.  I'll ask them again.

**Comment by platypii** [comment]
Alternative idea: have a list of open source licenses that are acceptable by webjars, even if it is a superset of the ones allowed by maven.

For licenses supported by bintray, set the license. For licenses not supported by bintray, upload with no license set.

It's not ideal since some license information would be lost for a tiny % of jars. But the whitelist would still keep it limited to open source software that should be legally fine to deploy as a webjar.

**Comment by jamesward** [comment]
Unfortunately BinTray doesn't allow packages without an "acceptable" license. I could change things to just go straight to Maven Central where there are no such restrictions.

**Comment by platypii** [comment]
I was able to work around this by not depending on npm. It was not really necessary upon closer inspection. Doesn't fix the underlying license issue, but it seems rare enough that maybe it's not a problem for most packages. Feel free to close issue #1903 if you like. Thanks for the responsiveness!

**Comment by jamesward** [comment]
Cool. I did have this escalated with BinTray.  So hopefully they resolve it at some point.  Keeping it up for tracking.

**Comment by jamesward** [comment]
Now that we are off Bintray, this is resolved.

**Pull request closed without merging**
