### PR TITLE
Bower sync

### PR DESCRIPTION
**Pull request by jamesward**

### CODE REVIEW

**Comment by mwanji** [comment]
Awesome! I tried to read through it the other day, but didn't really get it. Could you outline how this works?

**Comment by jamesward** [comment]
The full pipeline is:

1. Get the Bower package info using the [Bower Micro-service](https://github.com/jamesward/bower-as-a-service)
1. The licenses are determined using the [GitHub License Micro-service](https://github.com/jamesward/github-license-service)
1. Convert the NPM dependencies definitions to Maven dependencies (which involves converting NPM version ranges to Maven version ranges)
1. Create the pom
1. Get the Bower package's zip from the Bower micro-service
1. Turn the zip into a WebJar / Maven jar
1. Create the package on BinTray
1. Create the version on BinTray
1. Publish the pom, jar, and empty source jar
1. Sign the files
1. Publish the files on BinTray
1. Sync the files to Maven Central

That all works!  But it is kicked off manually via:

    java -cp "target/universal/stage/lib/*" utils.BowerWebJar jquery 1.11.0

The next step is to read the full Bower index periodically and do this automatically for anything that doesn't exist.

**Comment by mwanji** [comment]
Thanks. Why are the bower-synced webjars in a different groupId?

Also, org.webjars.bower:bootstrap:3.3.2 POM seems to be incorrect: http://search.maven.org/#artifactdetails|org.webjars.bower|bootstrap|3.3.2|jar

screenshot from 2015-03-10 10 37 05

**Comment by jamesward** [comment]
The different groupId is because I'm going to sync the whole Bower catalog and without it, there would be conflicts.  Also I plan on adding a `org.webjars.npm` groupId for the NPM sync.

The bootstrap 3.3.2 pom was broken when I first published it.  I've republished the artifacts but I don't think search.maven.org refreshes it's index.

**Comment by mwanji** [comment]
What would cause the conflicts? I had assumed that Bower sync would skip any existing versions. Changing the groupId will confuse people already using the lib. When they want to upgrade, will they have to check whether it's changed to a bower or npm groupId?

Also, I've noticed that more and more front-end libs are using npm and some libs are in both bower and npm. Would you sync the same lib from both?

**Comment by jamesward** [comment]
There will be some differences between the Bower, NPM, and Classic WebJars.  For instance, we can't do the RequireJS config in the Bower & NPM WebJars because that information can't be automatically assembled.  Also the Bower WebJars are basically just the git repo with the `bower.json` ignores applied, whereas the Classic WebJars are more curated (i.e. just the dist dir) and sometimes transformed (i.e. gz's).  The Bower & NPM catalogs will have more accurate / up-to-date dependency definitions.  So I think these catalogs will have to be different.  The aim for the Bower & NPM catalogs is just to be a mirror of those external catalogs, but in Maven Central.

Over time I see more people switching from the Classic WebJars to the Bower or NPM WebJars because they will be updated more quickly.

But these different catalogs does raise a usability issue (as you point out).  I'm not totally sure yet how to solve that.  So any thoughts on how to possibly do a combined catalog would be greatly appreciated.

**Comment by mwanji** [comment]
I thought syncing would be less ambitious. I'd imagined checking in bower/npm if a new version was out, then updating the existing POM with the new version number and updated deps.

This would work for the vast majority of libs, which are single file or just an extracted zip, but could fail if files, folder structure or Require-related things are changed. I don't know if there's an automated way of detecting that.

Perhaps there could be a review system: for build-time errors, but also after every update? Webjars.org could flag the latest version as pending review, and when somebody needs it, they could grab it from the Sonatype snapshots repo (or just check the list of files), verify that it works, then click a button that asks you to release it?

I don't know if any of that helps.

**Comment by jamesward** [comment]
I've deployed the Bower stuff.  Try it out: http://www.webjars.org/bower

**Comment by huntc** [comment]
Amazing. Well done James. Anything that you need from us on this?

**Comment by jamesward** [comment]
I think it just needs some testing.  Thanks @huntc!

**Pull request merged**
